# better https://www.cs.colby.edu/maxwell/courses/tutorials/maketutor/

CC=gcc
CFLAGS=-Wall -g
build_dir=../build


booker: main.c
	$(CC) $(CFLAGS) -o $(build_dir)/booker $<

run:
	$(build_dir)/booker